# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCONTC008():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cONTC008(self):
    self.driver.get("http://localhost:1667/")
    self.driver.set_window_size(772, 1030)
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Sign up\')]").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset/input").send_keys("com1")
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset[2]/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset[2]/input").send_keys("com1@com.com")
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset[3]/input").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/div/div/form/fieldset[3]/input").send_keys("Abcd1234")
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Sign up\')]").click()
  
